/* Experimental HDREZKA history layer. Safe to skip. */
(function(){
'use strict';
if(window.rezka4_history_layer)return;window.rezka4_history_layer=true;
var state={movie:null,season:0,episode:0};
function active(){try{var a=Lampa.Activity&&Lampa.Activity.active&&Lampa.Activity.active();return a&&a.component==='rezka4_online'?a:null}catch(e){return null}}
function num(v){var m=String(v||'').match(/(\d+)/);return m?parseInt(m[1],10)||0:0}
function syncMovie(){var a=active();if(a&&a.movie)state.movie=a.movie}
function bindChoices(){try{if(typeof window.$!=='function')return;syncMovie();$('.rezka4-ui:visible [data-r4-key^="season:"]').off('hover:enter.r4hist').on('hover:enter.r4hist',function(){state.season=num($(this).attr('data-r4-key'));state.episode=0});$('.rezka4-ui:visible [data-r4-key^="episode:"]').off('hover:enter.r4hist').on('hover:enter.r4hist',function(){state.episode=num($(this).attr('data-r4-key'))})}catch(e){console.log('REZKA4 history bind error',e)}}
function fromQuality(){try{if(typeof window.$!=='function')return;var ui=$('.rezka4-ui.r4-quality:visible,.rezka4-ui:visible').last();if(!ui.length)return;var t=String(ui.find('.rezka4-title').first().text()||''),s=String(ui.find('.rezka4-sub').first().text()||'');if(!state.episode)state.episode=num(t);if(!state.season){var m=s.match(/(?:сезон|season)\s*(\d+)/i);if(m)state.season=parseInt(m[1],10)||0}}catch(e){}}
function serial(movie){return !!(movie&&(movie.original_name||movie.first_air_date||movie.number_of_seasons||movie.media_type==='tv'||movie.type==='tv'))}
function timelineHash(movie,season,episode){try{if(!movie||!Lampa.Utils||!Lampa.Utils.hash)return null;var src;if(serial(movie)){if(!season||!episode)return null;src=String(season)+(season>10?':':'')+String(episode)+String(movie.original_name||movie.name||movie.title||'')}else src=String(movie.original_title||movie.title||movie.name||'');return src?Lampa.Utils.hash(src):null}catch(e){return null}}
function timelineFor(movie){try{if(!movie||!Lampa.Timeline||!Lampa.Timeline.view)return null;if(serial(movie))fromQuality();var hash=timelineHash(movie,state.season,state.episode);return hash!=null?Lampa.Timeline.view(hash):null}catch(e){return null}}
function enrich(data){try{syncMovie();var movie=state.movie;if(!movie||!data)return;var tl=timelineFor(movie);if(!tl)return;if(!data.timeline)data.timeline=tl;if(serial(movie)){data.season=state.season;data.episode=state.episode}if(Lampa.Favorite&&Lampa.Favorite.add)Lampa.Favorite.add('history',movie,100);data.rezka4_history=true;console.log('REZKA4 history attached',serial(movie)?('S'+state.season+'E'+state.episode):'movie')}catch(e){console.log('REZKA4 history attach error',e)}}
function hookPlayer(){try{if(!Lampa.Player||!Lampa.Player.play||window.rezka4_history_player_hook)return;window.rezka4_history_player_hook=true;var original=Lampa.Player.play;Lampa.Player.play=function(data){try{if(active())enrich(data)}catch(e){}return original.apply(this,arguments)}}catch(e){console.log('REZKA4 history player hook error',e)}}
function ensureProgressStyle(){if(document.getElementById('rezka4-history-style'))return;var s=document.createElement('style');s.id='rezka4-history-style';s.textContent='.rezka4-episode-percent,.rezka4-season-last{font-size:.6em;opacity:.72;margin-top:.28em;line-height:1;white-space:nowrap}.rezka4-duration-badge{position:absolute;right:.3em;top:.24em;padding:.12em .32em;border-radius:.32em;background:rgba(255,255,255,.1);font-size:.48em;font-weight:400;line-height:1.2;opacity:.72;white-space:nowrap;pointer-events:none}.rezka4-card.focus .rezka4-duration-badge{background:rgba(255,255,255,.18);opacity:1}.rezka4-episode-progress,.rezka4-season-progress{position:absolute;left:.32em;right:.32em;bottom:.18em;height:.1em;border-radius:1em;background:rgba(255,255,255,.14);overflow:hidden;pointer-events:none}.rezka4-episode-progress i,.rezka4-season-progress i{display:block;height:100%;background:rgba(255,255,255,.92);border-radius:inherit}.rezka4-card.focus .rezka4-episode-progress,.rezka4-card.focus .rezka4-season-progress{background:rgba(255,255,255,.3)}';document.head.appendChild(s)}
function roadFor(movie,season,episode){try{var hash=timelineHash(movie,season,episode),road=hash!=null&&Lampa.Timeline&&Lampa.Timeline.view?Lampa.Timeline.view(hash):null;if(road&&parseFloat(road.percent)>0)return road;if(Lampa.Timeline&&Lampa.Timeline.watchedEpisode){var alt=Lampa.Timeline.watchedEpisode(movie,season,episode,true);if(alt)return alt}return road}catch(e){return null}}
function episodeSeason(ui){var t=String(ui.find('.rezka4-title').first().text()||''),m=t.match(/(?:сезон|season)\s*(\d+)/i);return m?(parseInt(m[1],10)||0):(state.season||0)}
function minutesFromSeconds(v){var sec=Math.max(0,Math.floor(parseFloat(v)||0));if(!sec)return 0;return Math.max(1,Math.round(sec/60))}
function defaultRuntime(movie){try{var v=0;if(movie){if(Array.isArray(movie.episode_run_time)&&movie.episode_run_time.length)v=parseInt(movie.episode_run_time[0],10)||0;if(!v&&movie.last_episode_to_air)v=parseInt(movie.last_episode_to_air.runtime,10)||0;if(!v&&movie.next_episode_to_air)v=parseInt(movie.next_episode_to_air.runtime,10)||0;if(!v)v=parseInt(movie.runtime,10)||0}return v}catch(e){return 0}}
function knownRuntime(movie,season,episode,road){var exact=minutesFromSeconds(road&&road.duration);if(exact)return exact;var generic=defaultRuntime(movie);if(generic)return generic;try{for(var ep=1;ep<=50;ep++){var other=roadFor(movie,season,ep),m=minutesFromSeconds(other&&other.duration);if(m)return m}}catch(e){}return 0}
function resumeLabel(road,p){var seconds=Math.max(0,Math.floor(parseFloat(road&&road.time)||0));if(!seconds)return p+'%';var minute=Math.floor(seconds/60);return (minute<1?'<1 мин':minute+' мин')+' • '+p+'%'}
function showEpisodeProgress(){try{if(typeof window.$!=='function')return;syncMovie();var movie=state.movie,ui=$('.rezka4-ui.r4-episodes:visible').last();if(!movie||!ui.length)return;ensureProgressStyle();var season=episodeSeason(ui);if(!season)return;ui.find('[data-r4-key^="episode:"]').each(function(){var card=$(this),ep=num(card.attr('data-r4-key')),road=roadFor(movie,season,ep),p=Math.max(0,Math.min(100,Math.round(parseFloat(road&&road.percent)||0))),durationMin=knownRuntime(movie,season,ep,road);card.find('.rezka4-episode-percent,.rezka4-episode-progress,.rezka4-duration-badge').remove();if(durationMin)card.append('<div class="rezka4-duration-badge">'+durationMin+' мин</div>');if(!p)return;card.children('div').first().append('<div class="rezka4-episode-percent">'+resumeLabel(road,p)+'</div>');card.append('<div class="rezka4-episode-progress"><i style="width:'+p+'%"></i></div>')})}catch(e){console.log('REZKA4 episode progress error',e)}}
function seasonTotal(card){var saved=parseInt(card.attr('data-r4-total'),10)||0;if(saved)return saved;var meta=String(card.find('.rezka4-meta').first().text()||''),m=meta.match(/(\d+)/),total=m?(parseInt(m[1],10)||0):0;if(total)card.attr('data-r4-total',String(total));return total}
function showSeasonProgress(){try{if(typeof window.$!=='function')return;syncMovie();var movie=state.movie,ui=$('.rezka4-ui.r4-seasons:visible').last();if(!movie||!ui.length)return;ensureProgressStyle();ui.find('[data-r4-key^="season:"]').each(function(){var card=$(this),season=num(card.attr('data-r4-key')),total=seasonTotal(card);if(!season||!total)return;var done=0,sum=0,lastEp=0,lastP=0,lastRoad=null;for(var ep=1;ep<=total;ep++){var road=roadFor(movie,season,ep),p=Math.max(0,Math.min(100,Math.round(parseFloat(road&&road.percent)||0)));sum+=p;if(p>=90)done++;if(p>0){lastEp=ep;lastP=p;lastRoad=road}}card.find('.rezka4-season-last,.rezka4-season-progress').remove();if(!lastEp){card.find('.rezka4-meta').text('Серий: '+total);return}card.find('.rezka4-meta').text(done+'/'+total+' просмотрено'+(done===total?' ✓':''));var lastMin=minutesFromSeconds(lastRoad&&lastRoad.time),lastText='Серия '+lastEp+(lastMin?' • '+lastMin+' мин':'')+' • '+lastP+'%';card.children('div').first().append('<div class="rezka4-season-last">'+lastText+'</div>');var avg=Math.max(1,Math.min(100,Math.round(sum/total)));card.append('<div class="rezka4-season-progress"><i style="width:'+avg+'%"></i></div>')})}catch(e){console.log('REZKA4 season progress error',e)}}
function refresh(){syncMovie();bindChoices();showEpisodeProgress();showSeasonProgress()}
function install(){try{hookPlayer();refresh();if(typeof MutationObserver!=='undefined'&&document.body){var timer=0,o=new MutationObserver(function(){clearTimeout(timer);timer=setTimeout(refresh,35)});o.observe(document.body,{childList:true,subtree:true});window.rezka4_history_observer=o}if(Lampa.Listener){Lampa.Listener.follow('full',function(){setTimeout(refresh,30)});Lampa.Listener.follow('activity',function(){setTimeout(refresh,30)});Lampa.Listener.follow('player',function(){setTimeout(refresh,80)})}}catch(e){console.log('REZKA4 history install error',e)}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install,{once:true});else install();
})();
