/* Experimental HDREZKA history layer. Safe to skip. */
(function(){
'use strict';
if(window.rezka4_history_layer)return;window.rezka4_history_layer=true;
var state={movie:null,season:0,episode:0};
var runtimeCache={};
var SETTINGS_SCRIPT_URL=(document.currentScript&&document.currentScript.src)||'';
function active(){try{var a=Lampa.Activity&&Lampa.Activity.active&&Lampa.Activity.active();return a&&a.component==='rezka4_online'?a:null}catch(e){return null}}
function num(v){var m=String(v||'').match(/(\d+)/);return m?parseInt(m[1],10)||0:0}
function syncMovie(){var a=active();if(a&&a.movie)state.movie=a.movie}
function serial(movie){return !!(movie&&(movie.original_name||movie.first_air_date||movie.number_of_seasons||movie.media_type==='tv'||movie.type==='tv'))}
function timelineHash(movie,season,episode){try{if(!movie||!Lampa.Utils||!Lampa.Utils.hash)return null;var src;if(serial(movie)){if(!season||!episode)return null;src=String(season)+(season>10?':':'')+String(episode)+String(movie.original_name||movie.name||movie.title||'')}else src=String(movie.original_title||movie.title||movie.name||'');return src?Lampa.Utils.hash(src):null}catch(e){return null}}
function roadFor(movie,season,episode){try{var hash=timelineHash(movie,season,episode),road=hash!=null&&Lampa.Timeline&&Lampa.Timeline.view?Lampa.Timeline.view(hash):null;if(road&&(parseFloat(road.percent)>0||parseFloat(road.duration)>0))return road;if(Lampa.Timeline&&Lampa.Timeline.watchedEpisode){var alt=Lampa.Timeline.watchedEpisode(movie,season,episode,true);if(alt)return alt}return road}catch(e){return null}}
function bindChoices(){try{if(typeof window.$!=='function')return;syncMovie();$('.rezka4-ui:visible [data-r4-key^="season:"]').off('hover:enter.r4hist').on('hover:enter.r4hist',function(){state.season=num($(this).attr('data-r4-key'));state.episode=0});$('.rezka4-ui:visible [data-r4-key^="episode:"]').off('hover:enter.r4hist').on('hover:enter.r4hist',function(){state.episode=num($(this).attr('data-r4-key'))})}catch(e){}}
function fromQuality(){try{if(typeof window.$!=='function')return;var ui=$('.rezka4-ui.r4-quality:visible,.rezka4-ui:visible').last();if(!ui.length)return;var t=String(ui.find('.rezka4-title').first().text()||''),s=String(ui.find('.rezka4-sub').first().text()||'');if(!state.episode)state.episode=num(t);if(!state.season){var m=s.match(/(?:сезон|season)\s*(\d+)/i);if(m)state.season=parseInt(m[1],10)||0}}catch(e){}}
function timelineFor(movie){try{if(!movie||!Lampa.Timeline||!Lampa.Timeline.view)return null;if(serial(movie))fromQuality();var hash=timelineHash(movie,state.season,state.episode);return hash!=null?Lampa.Timeline.view(hash):null}catch(e){return null}}
function enrich(data){try{syncMovie();var movie=state.movie;if(!movie||!data)return;var tl=timelineFor(movie);if(!tl)return;if(!data.timeline)data.timeline=tl;if(serial(movie)){data.season=state.season;data.episode=state.episode}if(Lampa.Favorite&&Lampa.Favorite.add)Lampa.Favorite.add('history',movie,100);data.rezka4_history=true}catch(e){console.log('REZKA4 history attach error',e)}}
function hookPlayer(){try{if(!Lampa.Player||!Lampa.Player.play||window.rezka4_history_player_hook)return;window.rezka4_history_player_hook=true;var original=Lampa.Player.play;Lampa.Player.play=function(data){try{if(active())enrich(data)}catch(e){}return original.apply(this,arguments)}}catch(e){}}
function ensureStyle(){if(document.getElementById('rezka4-history-style'))return;var s=document.createElement('style');s.id='rezka4-history-style';s.textContent='.rezka4-episode-percent,.rezka4-season-last{font-size:.6em;opacity:.72;margin-top:.28em;line-height:1;white-space:nowrap}.rezka4-duration-badge{position:absolute;right:.3em;top:.24em;padding:.12em .32em;border-radius:.32em;background:rgba(255,255,255,.1);font-size:.48em;font-weight:400;line-height:1.2;opacity:.72;white-space:nowrap;pointer-events:none}.rezka4-card.focus .rezka4-duration-badge{background:rgba(255,255,255,.18);opacity:1}.rezka4-episode-progress,.rezka4-season-progress{position:absolute;left:.32em;right:.32em;bottom:.18em;height:.1em;border-radius:1em;background:rgba(255,255,255,.14);overflow:hidden;pointer-events:none}.rezka4-episode-progress i,.rezka4-season-progress i{display:block;height:100%;background:rgba(255,255,255,.92);border-radius:inherit}.rezka4-card.focus .rezka4-episode-progress,.rezka4-card.focus .rezka4-season-progress{background:rgba(255,255,255,.3)}';document.head.appendChild(s)}
function episodeSeason(ui){var t=String(ui.find('.rezka4-title').first().text()||''),m=t.match(/(?:сезон|season)\s*(\d+)/i);return m?(parseInt(m[1],10)||0):(state.season||0)}
function minutesFromSeconds(v){var sec=Math.max(0,Math.floor(parseFloat(v)||0));if(!sec)return 0;return Math.max(1,Math.round(sec/60))}
function localEpisodeRuntime(movie,season,episode){try{var lists=[];if(movie&&Array.isArray(movie.episodes))lists.push(movie.episodes);if(movie&&Array.isArray(movie.seasons)){for(var i=0;i<movie.seasons.length;i++){var s=movie.seasons[i];if((parseInt(s.season_number,10)||0)===season&&Array.isArray(s.episodes))lists.push(s.episodes)}}for(var l=0;l<lists.length;l++){for(var j=0;j<lists[l].length;j++){var e=lists[l][j],n=parseInt(e.episode_number||e.number,10)||0;if(n===episode){var r=parseInt(e.runtime,10)||0;if(r)return r}}}}catch(e){}return 0}
function tmdbId(movie){if(!movie)return 0;var id=parseInt(movie.tmdb_id,10)||0;if(id)return id;return parseInt(movie.id,10)||0}
function runtimeKey(movie,season){return String(tmdbId(movie))+'_'+String(season)}
function loadSeasonRuntimes(movie,season){try{var id=tmdbId(movie);if(!id||!season||!Lampa.Api||!Lampa.Api.sources||!Lampa.Api.sources.tmdb||!Lampa.Api.sources.tmdb.get)return;var key=runtimeKey(movie,season);if(runtimeCache[key]!==undefined)return;runtimeCache[key]=null;Lampa.Api.sources.tmdb.get('tv/'+id+'/season/'+season,{},function(data){var map={};var eps=data&&Array.isArray(data.episodes)?data.episodes:[];for(var i=0;i<eps.length;i++){var n=parseInt(eps[i].episode_number,10)||0,r=parseInt(eps[i].runtime,10)||0;if(n&&r)map[n]=r}runtimeCache[key]=map;setTimeout(refresh,20)},function(){runtimeCache[key]={}})}catch(e){console.log('REZKA4 runtime load error',e)}}
function exactEpisodeRuntime(movie,season,episode,road){var fromTimeline=minutesFromSeconds(road&&road.duration);if(fromTimeline)return fromTimeline;var local=localEpisodeRuntime(movie,season,episode);if(local)return local;var key=runtimeKey(movie,season),cached=runtimeCache[key];if(cached&&cached[episode])return cached[episode];loadSeasonRuntimes(movie,season);return 0}
function resumeLabel(road,p){var seconds=Math.max(0,Math.floor(parseFloat(road&&road.time)||0));if(!seconds)return p+'%';var minute=Math.floor(seconds/60);return (minute<1?'<1 мин':minute+' мин')+' • '+p+'%'}
function showEpisodeProgress(){try{if(typeof window.$!=='function')return;syncMovie();var movie=state.movie,ui=$('.rezka4-ui.r4-episodes:visible').last();if(!movie||!ui.length)return;ensureStyle();var season=episodeSeason(ui);if(!season)return;loadSeasonRuntimes(movie,season);ui.find('[data-r4-key^="episode:"]').each(function(){var card=$(this),ep=num(card.attr('data-r4-key')),road=roadFor(movie,season,ep),p=Math.max(0,Math.min(100,Math.round(parseFloat(road&&road.percent)||0))),durationMin=exactEpisodeRuntime(movie,season,ep,road);card.find('.rezka4-episode-percent,.rezka4-episode-progress,.rezka4-duration-badge').remove();if(durationMin)card.append('<div class="rezka4-duration-badge">'+durationMin+' мин</div>');if(!p)return;card.children('div').first().append('<div class="rezka4-episode-percent">'+resumeLabel(road,p)+'</div>');card.append('<div class="rezka4-episode-progress"><i style="width:'+p+'%"></i></div>')})}catch(e){console.log('REZKA4 episode progress error',e)}}
function seasonTotal(card){var saved=parseInt(card.attr('data-r4-total'),10)||0;if(saved)return saved;var meta=String(card.find('.rezka4-meta').first().text()||''),m=meta.match(/(\d+)/),total=m?(parseInt(m[1],10)||0):0;if(total)card.attr('data-r4-total',String(total));return total}
function showSeasonProgress(){try{if(typeof window.$!=='function')return;syncMovie();var movie=state.movie,ui=$('.rezka4-ui.r4-seasons:visible').last();if(!movie||!ui.length)return;ensureStyle();ui.find('[data-r4-key^="season:"]').each(function(){var card=$(this),season=num(card.attr('data-r4-key')),total=seasonTotal(card);if(!season||!total)return;var done=0,sum=0,lastEp=0,lastP=0,lastRoad=null;for(var ep=1;ep<=total;ep++){var road=roadFor(movie,season,ep),p=Math.max(0,Math.min(100,Math.round(parseFloat(road&&road.percent)||0)));sum+=p;if(p>=90)done++;if(p>0){lastEp=ep;lastP=p;lastRoad=road}}card.find('.rezka4-season-last,.rezka4-season-progress').remove();if(!lastEp){card.find('.rezka4-meta').text('Серий: '+total);return}card.find('.rezka4-meta').text(done+'/'+total+' просмотрено'+(done===total?' ✓':''));var lastMin=minutesFromSeconds(lastRoad&&lastRoad.time),lastText='Серия '+lastEp+(lastMin?' • '+lastMin+' мин':'')+' • '+lastP+'%';card.children('div').first().append('<div class="rezka4-season-last">'+lastText+'</div>');var avg=Math.max(1,Math.min(100,Math.round(sum/total)));card.append('<div class="rezka4-season-progress"><i style="width:'+avg+'%"></i></div>')})}catch(e){console.log('REZKA4 season progress error',e)}}
function cfg(k){try{return Lampa.Storage.get(k)||''}catch(e){return''}}
function cfgSource(){var s=String(cfg('rezka_source')||cfg('rezka_domain')||cfg('rezka_url')||'').trim();if(s&&!/^[a-z][a-z0-9+.-]*:\/\//i.test(s))s='https://'+s;return s.replace(/\/+$/,'')}
function cfgProxy(){var s=String(cfg('rezka_proxy')||cfg('rezka_proxy_url')||'').trim();if(!s){try{var u=new URL(SETTINGS_SCRIPT_URL,location.href);s=u.origin+'/'}catch(e){}}if(s&&!/^[a-z][a-z0-9+.-]*:\/\//i.test(s))s='https://'+s;if(s.indexOf('{url}')>=0)return s;if(/[?&]url=$/i.test(s))return s;if(/[?&]url=/i.test(s))return s.replace(/([?&]url=)[^&]*/i,'$1');return s?s+(s.indexOf('?')>=0?'&':'?')+'url=':''}
function cfgUrl(proxy,target){return proxy.indexOf('{url}')>=0?proxy.replace('{url}',encodeURIComponent(target)):proxy+encodeURIComponent(target)}
function notify(text){try{Lampa.Noty.show(text)}catch(e){}}
function testSettingsCompat(){try{var source=cfgSource(),proxy=cfgProxy(),login=cfg('rezka_login')||cfg('rezka2_login'),password=cfg('rezka_password')||cfg('rezka2_password');if(!source)return notify('HDREZKA: укажите адрес источника');if(!proxy)return notify('HDREZKA: укажите адрес proxy');if(!login||!password)return notify('HDREZKA: укажите логин и пароль');var sid=cfg('rezka_proxy_session')||('tv-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,12));try{Lampa.Storage.set('rezka_proxy_session',sid)}catch(e){}function request(method,target,body,done,fail){var x=new XMLHttpRequest();x.open(method,cfgUrl(proxy,target),true);x.timeout=20000;x.setRequestHeader('X-Requested-With','XMLHttpRequest');x.setRequestHeader('X-Lampa-Session',sid);if(method==='POST')x.setRequestHeader('Content-Type','application/x-www-form-urlencoded');x.onload=function(){x.status>=200&&x.status<300?done(x.responseText):fail('HTTP '+x.status)};x.onerror=function(){fail('Сетевая ошибка')};x.ontimeout=function(){fail('Таймаут')};x.send(body||null)}notify('HDREZKA: проверяем подключение…');request('GET',source+'/',null,function(){var body='login_name='+encodeURIComponent(login)+'&login_password='+encodeURIComponent(password)+'&login_not_save=0';request('POST',source+'/ajax/login/?t='+Date.now(),body,function(text){var j;try{j=JSON.parse(text)}catch(e){}if(j&&j.success===false)return notify('HDREZKA: '+(j.message||'ошибка входа'));notify('HDREZKA: подключение и авторизация работают')},function(err){notify('HDREZKA: '+err)})},function(err){notify('HDREZKA: '+err)})}catch(e){notify('HDREZKA: '+String(e.message||e))}}
function settingsIcon(){return'<svg viewBox="0 0 24 24" width="28" height="28" fill="currentColor"><path d="M8 5h8l1 2h3v4h-2.1a6 6 0 0 1 0 2H20v4h-3l-1 2H8l-1-2H4v-4h2.1a6 6 0 0 1 0-2H4V7h3l1-2Zm4 4a3 3 0 1 0 0 6 3 3 0 0 0 0-6Z"/></svg>'}
function resetSettingsRegistry(){try{if(!Lampa.SettingsApi)return false;if(Lampa.SettingsApi.removeComponent)Lampa.SettingsApi.removeComponent('rezka4');else{if(Lampa.SettingsApi.removeParams)Lampa.SettingsApi.removeParams('rezka4');try{var allp=Lampa.SettingsApi.allParams&&Lampa.SettingsApi.allParams();if(allp)delete allp.rezka4}catch(e){}try{var allc=Lampa.SettingsApi.allComponents&&Lampa.SettingsApi.allComponents();if(allc)delete allc.rezka4}catch(e){}}Lampa.SettingsApi.addComponent({component:'rezka4',name:'HDREZKA',icon:settingsIcon()});function input(name,title,description,placeholder,onRender){Lampa.SettingsApi.addParam({component:'rezka4',param:{name:name,type:'input',values:'',placeholder:placeholder||'',default:''},field:{name:title,description:description||''},onRender:onRender})}input('rezka_login','Логин','Логин или email учётной записи HDREZKA','Логин или email');input('rezka_password','Пароль','Пароль хранится только локально в Lampa','Введите пароль',function(item){setTimeout(function(){try{var value=cfg('rezka_password');if(value)item.find('.settings-param__value').text('••••••••')}catch(e){}},0)});input('rezka_source','Источник HDREZKA','Полный адрес доступного зеркала без дополнительных путей','https://example.com');input('rezka_proxy','Адрес proxy','Можно оставить пустым: адрес определяется по месту загрузки plugin.js. Поддерживается шаблон {url}','https://proxy.example/?url=');Lampa.SettingsApi.addParam({component:'rezka4',param:{type:'button'},field:{name:'Проверить подключение',description:'Проверить источник, proxy, логин и пароль'},onChange:testSettingsCompat});window.rezka4_settings_ready=true;window.rezka4_settings_input_fixed=true;return true}catch(e){console.log('REZKA4 settings reset error',e);return false}}
function scheduleSettingsRepair(){if(window.rezka4_settings_registry_fixed)return;var tries=0;function step(){if(resetSettingsRegistry()){window.rezka4_settings_registry_fixed=true;return}if(tries++<40)setTimeout(step,250)}step()}
function refresh(){syncMovie();bindChoices();showEpisodeProgress();showSeasonProgress()}
function install(){try{scheduleSettingsRepair();hookPlayer();refresh();if(typeof MutationObserver!=='undefined'&&document.body){var timer=0,o=new MutationObserver(function(){clearTimeout(timer);timer=setTimeout(refresh,35)});o.observe(document.body,{childList:true,subtree:true});window.rezka4_history_observer=o}if(Lampa.Listener){Lampa.Listener.follow('full',function(){setTimeout(refresh,30)});Lampa.Listener.follow('activity',function(){setTimeout(refresh,30)});Lampa.Listener.follow('player',function(){setTimeout(refresh,80)});Lampa.Listener.follow('app',function(e){if(e&&e.type==='ready')setTimeout(scheduleSettingsRepair,20)})}}catch(e){console.log('REZKA4 history install error',e)}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install,{once:true});else install();
})();
