/* Experimental HDREZKA history layer. Safe to skip. */
(function(){
'use strict';
if(window.rezka4_history_layer)return;window.rezka4_history_layer=true;
var state={movie:null,movieKey:'',season:0,episode:0,catalog:[]};
var runtimeCache={};
var refreshTimer=0;
var SETTINGS_SCRIPT_URL=(document.currentScript&&document.currentScript.src)||'';
function active(){try{var a=Lampa.Activity&&Lampa.Activity.active&&Lampa.Activity.active();return a&&a.component==='rezka4_online'?a:null}catch(e){return null}}
function num(v){var m=String(v||'').match(/(\d+)/);return m?parseInt(m[1],10)||0:0}
function movieKey(movie){if(!movie)return'';var id=movie.tmdb_id||movie.id||movie.imdb_id||'',name=movie.original_name||movie.original_title||movie.name||movie.title||'',date=movie.first_air_date||movie.release_date||'';return(serial(movie)?'tv:':'movie:')+String(id||name).toLowerCase()+':'+String(date).slice(0,4)}
function syncMovie(movie){var a=active(),next=movie||(a&&a.movie);if(!next)return;var key=movieKey(next);if(key!==state.movieKey){state.movieKey=key;state.season=0;state.episode=0;state.catalog=[]}state.movie=next}
function serial(movie){return !!(movie&&(movie.original_name||movie.first_air_date||movie.number_of_seasons||movie.media_type==='tv'||movie.type==='tv'))}
function timelineHash(movie,season,episode){try{if(!movie||!Lampa.Utils||!Lampa.Utils.hash)return null;var src;if(serial(movie)){if(!season||!episode)return null;src=String(season)+(season>10?':':'')+String(episode)+String(movie.original_name||movie.name||movie.title||'')}else src=String(movie.original_title||movie.title||movie.name||'');return src?Lampa.Utils.hash(src):null}catch(e){return null}}
function roadFor(movie,season,episode){try{var hash=timelineHash(movie,season,episode),road=hash!=null&&Lampa.Timeline&&Lampa.Timeline.view?Lampa.Timeline.view(hash):null;if(road&&(parseFloat(road.percent)>0||parseFloat(road.duration)>0))return road;if(Lampa.Timeline&&Lampa.Timeline.watchedEpisode){var alt=Lampa.Timeline.watchedEpisode(movie,season,episode,true);if(alt)return alt}return road}catch(e){return null}}
function episodeCatalog(catalog,season){var out=[],seen={};(Array.isArray(catalog)?catalog:[]).forEach(function(item){var s=num(item&&(item.season_id||item.season||item.season_number)),e=num(item&&(item.episode_id||item.episode||item.episode_number||item.id));if(!s||!e||(season&&s!==season))return;var key=s+':'+e;if(seen[key])return;seen[key]=true;out.push({season:s,episode:e,item:item})});out.sort(function(a,b){return a.season-b.season||a.episode-b.episode});for(var i=0;i<out.length;i++)out[i].index=i;return out}
function rawPercent(road){return Math.max(0,Math.min(100,parseFloat(road&&road.percent)||0))}
function episodeStates(movie,catalog,season){var items=episodeCatalog(catalog,season);for(var i=0;i<items.length;i++){var road=roadFor(movie,items[i].season,items[i].episode),percent=rawPercent(road);items[i].road=road;items[i].percent=percent;items[i].updated=Math.max(0,parseFloat(road&&road.updated)||0);items[i].status=percent>=90?'watched':(percent>0?'in_progress':'new')}return items}
function latestActivity(items){var latest=null;for(var i=0;i<items.length;i++){var item=items[i];if(item.percent<=0)continue;if(!latest||item.updated>latest.updated||(item.updated===latest.updated&&item.index>latest.index))latest=item}return latest}
function asChoice(item,kind){if(!item)return null;item.kind=kind;return item}
function choiceItems(items,resumeOnly){var latest=latestActivity(items),i,resume=null;if(!items.length||!latest)return resumeOnly?null:asChoice(items[0],'start');var allComplete=true;for(i=0;i<items.length;i++)if(items[i].status!=='watched'){allComplete=false;break}if(allComplete)return resumeOnly?null:asChoice(items[items.length-1],'complete');if(latest.status==='in_progress')return asChoice(latest,'resume');for(i=latest.index+1;i<items.length;i++)if(items[i].status!=='watched')return asChoice(items[i],items[i].status==='in_progress'?'resume':'next');if(resumeOnly){for(i=0;i<=latest.index;i++)if(items[i].status==='in_progress'&&(!resume||items[i].updated>resume.updated||(items[i].updated===resume.updated&&items[i].index>resume.index)))resume=items[i];return resume?asChoice(resume,'resume'):null}for(i=0;i<=latest.index;i++)if(items[i].status!=='watched')return asChoice(items[i],items[i].status==='in_progress'?'resume':'next');return asChoice(latest,'complete')}
function choice(movie,catalog,season,resumeOnly){return choiceItems(episodeStates(movie,catalog,season),resumeOnly)}
function pickResume(movie,catalog){return choice(movie,catalog,0,true)}
function pickEpisode(movie,season,catalog){return choice(movie,catalog,num(season),false)}
function pickTarget(movie,catalog){return choice(movie,catalog,0,false)}
function pickSeason(movie,catalog){var target=pickTarget(movie,catalog);return target?target.season:0}
function setCatalog(movie,catalog){syncMovie(movie);state.catalog=episodeCatalog(catalog,0).map(function(entry){return entry.item});return state.catalog.slice()}
function summaryFromStates(season,items,target){var watched=0,sum=0;for(var i=0;i<items.length;i++){if(items[i].status==='watched'){watched++;sum+=100}else sum+=items[i].percent}return{season:num(season),total:items.length,watched:watched,percent:items.length?Math.round(sum/items.length):0,complete:!!items.length&&watched===items.length,latest:latestActivity(items),target:target&&num(target.season)===num(season)?target:null,items:items}}
function seasonSummary(movie,season,catalog,target){return summaryFromStates(season,episodeStates(movie,catalog,num(season)),target)}
function titleSummary(movie,catalog,options){if(!serial(movie)){var road=roadFor(movie,0,0),percent=rawPercent(road),status=percent>=90?'watched':(percent>0?'in_progress':'new');return{available:true,exact:true,media:'movie',status:status,hasProgress:percent>0,total:1,watched:status==='watched'?1:0,percent:percent,updated:percent>0?Math.max(0,parseFloat(road&&road.updated)||0):0,road:road||null,target:null,latest:null}}var items=episodeStates(movie,catalog,0),exact=options===true||!!(options&&options.exact);if(!items.length)return{available:false,exact:false,media:'series',status:'unknown',hasProgress:false,total:0,watched:0,percent:0,updated:0,target:null,latest:null,items:[]};var target=choiceItems(items,false),latest=latestActivity(items),watched=0,sum=0;for(var i=0;i<items.length;i++){if(items[i].status==='watched'){watched++;sum+=100}else sum+=items[i].percent}var complete=watched===items.length,status=complete?'watched':(latest?'in_progress':'new');return{available:true,exact:exact,media:'series',status:status,hasProgress:!!latest,total:items.length,watched:watched,percent:Math.round(sum/items.length),updated:Math.max(0,parseFloat(latest&&latest.updated)||0),target:target||null,latest:latest||null,items:items}}
function setSelection(movie,season,episode){syncMovie(movie);state.season=num(season);state.episode=num(episode)}
function bindChoices(){try{if(typeof window.$!=='function')return;syncMovie();$('.rezka4-ui:visible [data-r4-key^="season:"]').off('hover:enter.r4hist').on('hover:enter.r4hist',function(){state.season=num($(this).attr('data-r4-key'));state.episode=0});$('.rezka4-ui:visible [data-r4-key^="episode:"]').off('hover:enter.r4hist').on('hover:enter.r4hist',function(){state.episode=num($(this).attr('data-r4-key'))})}catch(e){}}
function fromQuality(){try{if(typeof window.$!=='function')return;var ui=$('.rezka4-ui.r4-quality:visible,.rezka4-ui:visible').last();if(!ui.length)return;var t=String(ui.find('.rezka4-title').first().text()||''),s=String(ui.find('.rezka4-sub').first().text()||'');if(!state.episode)state.episode=num(t);if(!state.season){var m=s.match(/(?:сезон|season)\s*(\d+)/i);if(m)state.season=parseInt(m[1],10)||0}}catch(e){}}
function timelineFor(movie,season,episode){try{if(!movie||!Lampa.Timeline||!Lampa.Timeline.view)return null;if(serial(movie)&&(!season||!episode)){fromQuality();season=state.season;episode=state.episode}var hash=timelineHash(movie,season,episode);return hash!=null?Lampa.Timeline.view(hash):null}catch(e){return null}}
function enrich(data){try{syncMovie();var movie=state.movie;if(!movie||!data)return;var season=num(data.season||data.rezka4_season||state.season),episode=num(data.episode||data.rezka4_episode||state.episode);if(serial(movie)&&season&&episode&&!data.rezka4_defer_selection)setSelection(movie,season,episode);var tl=data.timeline||timelineFor(movie,season,episode);if(!tl)return;if(!data.timeline)data.timeline=tl;if(serial(movie)){data.season=season;data.episode=episode}if(Lampa.Favorite&&Lampa.Favorite.add)Lampa.Favorite.add('history',movie,100);data.rezka4_history=true}catch(e){console.log('REZKA4 history attach error',e)}}
function hookPlayer(){try{if(!Lampa.Player||!Lampa.Player.play||window.rezka4_history_player_hook)return;window.rezka4_history_player_hook=true;var original=Lampa.Player.play;Lampa.Player.play=function(data){try{if(active())enrich(data)}catch(e){}return original.apply(this,arguments)}}catch(e){}}
function nextNotice(text){try{Lampa.Noty.show('HDREZKA: '+text)}catch(e){}}
function ensurePlayerNavStyle(){if(document.getElementById('rezka4-player-nav-style'))return;var s=document.createElement('style');s.id='rezka4-player-nav-style';s.textContent='.rezka4-player-nextbox{display:flex!important}.rezka4-player-next{position:relative}.rezka4-player-next.is-loading{opacity:.45!important;pointer-events:none!important}.rezka4-player-next .tooltip{white-space:nowrap}';document.head.appendChild(s)}
function activatePlayerData(data){try{var activate=data&&data.rezka4_activate;if(data)delete data.rezka4_activate;if(typeof activate==='function')activate()}catch(e){}}
function playLoadedEpisode(nextData){if(!nextData||!nextData.url)return nextNotice('следующая серия недоступна');activatePlayerData(nextData);try{Lampa.Player.play(nextData);Lampa.Player.playlist([nextData])}catch(e){nextNotice('не удалось переключить серию')}}
function installPlayerEpisodeNav(){try{if(window.rezka4_player_episode_nav||!Lampa.Player||!Lampa.Player.listener)return;window.rezka4_player_episode_nav=true;ensurePlayerNavStyle();var token=0;function remove(){try{$('.rezka4-player-nextbox').remove()}catch(e){}}function attach(data,myToken){remove();var next=data&&data.rezka4_next;if(!next||typeof next.load!=='function')return;var tries=0;function step(){if(myToken!==token)return;var left=$('.player-panel__left').first();if(!left.length){if(tries++<40)return setTimeout(step,100);return}if(left.find('.rezka4-player-nextbox').length)return;var box=$('<div class="player-panel__box-buttons rezka4-player-nextbox"></div>'),button=$('<div class="rezka4-player-next button selector"><svg><use xlink:href="#sprite-player-next"></use></svg><div class="tooltip">Следующая серия</div></div>'),loading=false;button.on('hover:enter click',function(){if(loading||myToken!==token)return;loading=true;button.addClass('is-loading');nextNotice('загружаем следующую серию…');try{next.load(function(nextData){if(myToken!==token)return;loading=false;button.removeClass('is-loading');playLoadedEpisode(nextData)},function(err){loading=false;button.removeClass('is-loading');nextNotice(String(err||'не удалось загрузить следующую серию'))})}catch(e){loading=false;button.removeClass('is-loading');nextNotice(String(e&&e.message||e))}});box.append(button);left.append(box)}step()}Lampa.Player.listener.follow('start',function(data){token++;attach(data,token)});Lampa.Player.listener.follow('destroy',function(){token++;remove()})}catch(e){console.log('REZKA4 player nav error',e)}}
function ensureStyle(){if(document.getElementById('rezka4-history-style'))return;var s=document.createElement('style');s.id='rezka4-history-style';s.textContent='.rezka4-episode-state,.rezka4-season-last{max-width:100%;font-size:.58em;opacity:.74;margin-top:.3em;line-height:1.08;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;pointer-events:none}.rezka4-ui.r4-episodes .rezka4-card:not(.rezka4-back){min-height:4.2em!important}.rezka4-ui.r4-seasons .rezka4-card:not(.rezka4-back){min-height:4.75em!important}.rezka4-duration-badge{position:absolute;right:.3em;top:.24em;padding:.12em .32em;border-radius:.32em;background:rgba(255,255,255,.1);font-size:.48em;font-weight:400;line-height:1.2;opacity:.72;white-space:nowrap;pointer-events:none}.rezka4-card.focus .rezka4-duration-badge{background:rgba(255,255,255,.18);opacity:1}.rezka4-episode-progress,.rezka4-season-progress{position:absolute;left:.32em;right:.32em;bottom:.18em;height:.11em;border-radius:1em;background:rgba(255,255,255,.14);overflow:hidden;pointer-events:none}.rezka4-episode-progress i,.rezka4-season-progress i{display:block;height:100%;background:#39d66f;border-radius:inherit}.rezka4-card.focus .rezka4-episode-progress,.rezka4-card.focus .rezka4-season-progress{background:rgba(255,255,255,.3)}.rezka4-ui .rezka4-card.r4-status-watched:not(.focus),.rezka4-ui .rezka4-card.r4-season-complete:not(.focus){opacity:.52!important}.rezka4-ui .rezka4-card.r4-target:not(.focus),.rezka4-ui .rezka4-card.r4-season-target:not(.focus){opacity:1!important;background:rgba(57,214,111,.075)!important;border-color:rgba(57,214,111,.28)!important}.rezka4-ui .rezka4-card.r4-target .rezka4-episode-state,.rezka4-ui .rezka4-card.r4-season-target .rezka4-season-last{color:#63e58d;opacity:1}';document.head.appendChild(s)}
function episodeSeason(ui){var t=String(ui.find('.rezka4-title').first().text()||''),m=t.match(/(?:сезон|season)\s*(\d+)/i);return m?(parseInt(m[1],10)||0):(state.season||0)}
function minutesFromSeconds(v){var sec=Math.max(0,Math.floor(parseFloat(v)||0));if(!sec)return 0;return Math.max(1,Math.round(sec/60))}
function localEpisodeRuntime(movie,season,episode){try{var lists=[];if(movie&&Array.isArray(movie.episodes))lists.push(movie.episodes);if(movie&&Array.isArray(movie.seasons)){for(var i=0;i<movie.seasons.length;i++){var s=movie.seasons[i];if((parseInt(s.season_number,10)||0)===season&&Array.isArray(s.episodes))lists.push(s.episodes)}}for(var l=0;l<lists.length;l++){for(var j=0;j<lists[l].length;j++){var e=lists[l][j],n=parseInt(e.episode_number||e.number,10)||0;if(n===episode){var r=parseInt(e.runtime,10)||0;if(r)return r}}}}catch(e){}return 0}
function tmdbId(movie){if(!movie)return 0;var id=parseInt(movie.tmdb_id,10)||0;if(id)return id;return parseInt(movie.id,10)||0}
function runtimeKey(movie,season){return String(tmdbId(movie))+'_'+String(season)}
function loadSeasonRuntimes(movie,season){try{var id=tmdbId(movie);if(!id||!season||!Lampa.Api||!Lampa.Api.sources||!Lampa.Api.sources.tmdb||!Lampa.Api.sources.tmdb.get)return;var key=runtimeKey(movie,season);if(runtimeCache[key]!==undefined)return;runtimeCache[key]=null;Lampa.Api.sources.tmdb.get('tv/'+id+'/season/'+season,{},function(data){var map={};var eps=data&&Array.isArray(data.episodes)?data.episodes:[];for(var i=0;i<eps.length;i++){var n=parseInt(eps[i].episode_number,10)||0,r=parseInt(eps[i].runtime,10)||0;if(n&&r)map[n]=r}runtimeCache[key]=map;scheduleRefresh(20)},function(){runtimeCache[key]={}})}catch(e){console.log('REZKA4 runtime load error',e)}}
function exactEpisodeRuntime(movie,season,episode,road){var fromTimeline=minutesFromSeconds(road&&road.duration);if(fromTimeline)return fromTimeline;var local=localEpisodeRuntime(movie,season,episode);if(local)return local;var key=runtimeKey(movie,season),cached=runtimeCache[key];if(cached&&cached[episode])return cached[episode];loadSeasonRuntimes(movie,season);return 0}
function resumeLabel(road,p){var seconds=Math.max(0,Math.floor(parseFloat(road&&road.time)||0));if(!seconds)return p+'%';var minute=Math.floor(seconds/60);return (minute<1?'<1 мин':minute+' мин')+' • '+p+'%'}
function episodeUiCatalog(ui,season){var out=[];ui.find('[data-r4-key^="episode:"]').each(function(){var episode=num($(this).attr('data-r4-key'));if(episode)out.push({season_id:season,episode_id:episode})});return out}
function sameTarget(target,item){return !!(target&&item&&num(target.season)===num(item.season)&&num(target.episode)===num(item.episode))}
function showEpisodeProgress(){try{if(typeof window.$!=='function')return;syncMovie();var movie=state.movie,ui=$('.rezka4-ui.r4-episodes:visible').last();if(!movie||!ui.length)return;ensureStyle();var season=episodeSeason(ui);if(!season)return;loadSeasonRuntimes(movie,season);var items=episodeStates(movie,episodeUiCatalog(ui,season),season),target=choiceItems(items,false),byEpisode={};for(var i=0;i<items.length;i++)byEpisode[items[i].episode]=items[i];ui.find('[data-r4-key^="episode:"]').each(function(){var card=$(this),ep=num(card.attr('data-r4-key')),item=byEpisode[ep];if(!item)return;var road=item.road,p=Math.max(0,Math.min(item.status==='in_progress'?89:100,Math.floor(item.percent))),shown=item.status==='watched'?100:p,durationMin=exactEpisodeRuntime(movie,season,ep,road),targetKind=sameTarget(target,item)?String(target.kind||''):'',isTarget=!!targetKind&&targetKind!=='complete',label=item.status==='watched'?'✓ Просмотрено':(item.status==='in_progress'?'▶ '+resumeLabel(road,p):(isTarget?'Следующая':'')),signature=[state.movieKey,season,ep,item.status,item.percent.toFixed(3),parseFloat(road&&road.time)||0,parseFloat(road&&road.duration)||0,durationMin,targetKind].join('|');if(card.attr('data-r4-history-signature')===signature)return;card.attr('data-r4-history-signature',signature).attr('data-r4-progress-state',item.status).removeClass('r4-status-new r4-status-progress r4-status-watched r4-target').addClass(item.status==='watched'?'r4-status-watched':(item.status==='in_progress'?'r4-status-progress':'r4-status-new'));if(isTarget)card.addClass('r4-target');card.find('.rezka4-episode-percent,.rezka4-episode-state,.rezka4-episode-progress,.rezka4-duration-badge').remove();if(durationMin)$('<div class="rezka4-duration-badge"></div>').text(durationMin+' мин').appendTo(card);if(label)$('<div class="rezka4-episode-state"></div>').text(label).appendTo(card.children('div').first());if(shown)card.append('<div class="rezka4-episode-progress"><i style="width:'+shown+'%"></i></div>')})}catch(e){console.log('REZKA4 episode progress error',e)}}
function seasonTotal(card){var saved=parseInt(card.attr('data-r4-total'),10)||0;if(saved)return saved;var meta=String(card.find('.rezka4-meta').first().text()||''),m=meta.match(/(\d+)/),total=m?(parseInt(m[1],10)||0):0;if(total)card.attr('data-r4-total',String(total));return total}
function seasonUiCatalog(ui){var out=[];ui.find('[data-r4-key^="season:"]').each(function(){var card=$(this),season=num(card.attr('data-r4-key')),list=this.rezka4Episodes;if(Array.isArray(list)&&list.length)out=out.concat(list);else String(card.attr('data-r4-episodes')||'').split(',').forEach(function(value){var episode=num(value);if(season&&episode)out.push({season_id:season,episode_id:episode})})});return out.length?out:state.catalog.slice()}
function showSeasonProgress(){try{if(typeof window.$!=='function')return;syncMovie();var movie=state.movie,ui=$('.rezka4-ui.r4-seasons:visible').last();if(!movie||!ui.length)return;ensureStyle();var all=episodeStates(movie,seasonUiCatalog(ui),0),target=choiceItems(all,false),bySeason={};for(var i=0;i<all.length;i++){var key=all[i].season;if(!bySeason[key])bySeason[key]=[];bySeason[key].push(all[i])}ui.find('[data-r4-key^="season:"]').each(function(){var card=$(this),season=num(card.attr('data-r4-key')),items=bySeason[season]||[],summary=summaryFromStates(season,items,target);if(!season||!summary.total)return;var isTarget=!!summary.target&&summary.target.kind!=='complete',hasActivity=!!summary.latest,meta=summary.complete?'✓ '+summary.watched+'/'+summary.total+' просмотрено':((hasActivity||isTarget)?summary.watched+'/'+summary.total+' просмотрено':'Серий: '+summary.total),lastText='',last=summary.latest;if(summary.complete)lastText='✓ Просмотрено';else if(isTarget&&summary.target.kind==='resume'){var resumeP=Math.max(0,Math.min(89,Math.floor(summary.target.percent)));lastText='▶ С'+summary.target.episode+' • '+resumeP+'%'}else if(isTarget)lastText='Следующая • С'+summary.target.episode;else if(last){var lastP=Math.max(0,Math.min(last.status==='in_progress'?89:100,Math.floor(last.percent)));lastText='С'+last.episode+' • '+lastP+'%'}var signature=[state.movieKey,season,summary.total,summary.watched,summary.percent,summary.complete?'complete':'open',meta,lastText,summary.target&&summary.target.kind||''].join('|');if(card.attr('data-r4-history-signature')===signature)return;card.attr('data-r4-history-signature',signature).attr('data-r4-progress-state',summary.complete?'watched':(hasActivity?'in_progress':'new')).removeClass('r4-season-complete r4-season-progressed r4-season-target');if(summary.complete)card.addClass('r4-season-complete');else if(hasActivity)card.addClass('r4-season-progressed');if(isTarget)card.addClass('r4-season-target');var metaNode=card.find('.rezka4-meta').first();if(metaNode.text()!==meta)metaNode.text(meta);card.find('.rezka4-season-last,.rezka4-season-progress').remove();if(lastText)$('<div class="rezka4-season-last"></div>').text(lastText).appendTo(card.children('div').first());if(summary.percent)card.append('<div class="rezka4-season-progress"><i style="width:'+summary.percent+'%"></i></div>')})}catch(e){console.log('REZKA4 season progress error',e)}}
function cfg(k){try{return Lampa.Storage.get(k)||''}catch(e){return''}}
function cfgSource(){var s=String(cfg('rezka_source')||cfg('rezka_domain')||cfg('rezka_url')||'').trim();if(s&&!/^[a-z][a-z0-9+.-]*:\/\//i.test(s))s='https://'+s;return s.replace(/\/+$/,'')}
function cfgProxy(){var s=String(cfg('rezka_proxy')||cfg('rezka_proxy_url')||'').trim();if(!s){try{var u=new URL(SETTINGS_SCRIPT_URL,location.href);s=u.origin+'/'}catch(e){}}if(s&&!/^[a-z][a-z0-9+.-]*:\/\//i.test(s))s='https://'+s;if(s.indexOf('{url}')>=0)return s;if(/[?&]url=$/i.test(s))return s;if(/[?&]url=/i.test(s))return s.replace(/([?&]url=)[^&]*/i,'$1');return s?s+(s.indexOf('?')>=0?'&':'?')+'url=':''}
function cfgUrl(proxy,target){return proxy.indexOf('{url}')>=0?proxy.replace('{url}',encodeURIComponent(target)):proxy+encodeURIComponent(target)}
function notify(text){try{Lampa.Noty.show(text)}catch(e){}}
function testSettingsCompat(){try{var source=cfgSource(),proxy=cfgProxy(),login=cfg('rezka_login')||cfg('rezka2_login'),password=cfg('rezka_password')||cfg('rezka2_password');if(!source)return notify('HDREZKA: укажите адрес источника');if(!proxy)return notify('HDREZKA: укажите адрес proxy');if(!login||!password)return notify('HDREZKA: укажите логин и пароль');var sid=cfg('rezka_proxy_session')||('tv-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,12));try{Lampa.Storage.set('rezka_proxy_session',sid)}catch(e){}function request(method,target,body,done,fail){var x=new XMLHttpRequest();x.open(method,cfgUrl(proxy,target),true);x.timeout=20000;x.setRequestHeader('X-Requested-With','XMLHttpRequest');x.setRequestHeader('X-Lampa-Session',sid);if(method==='POST')x.setRequestHeader('Content-Type','application/x-www-form-urlencoded');x.onload=function(){x.status>=200&&x.status<300?done(x.responseText):fail('HTTP '+x.status)};x.onerror=function(){fail('Сетевая ошибка')};x.ontimeout=function(){fail('Таймаут')};x.send(body||null)}notify('HDREZKA: проверяем подключение…');request('GET',source+'/',null,function(){var body='login_name='+encodeURIComponent(login)+'&login_password='+encodeURIComponent(password)+'&login_not_save=0';request('POST',source+'/ajax/login/?t='+Date.now(),body,function(text){var j;try{j=JSON.parse(text)}catch(e){}if(j&&j.success===false)return notify('HDREZKA: '+(j.message||'ошибка входа'));notify('HDREZKA: подключение и авторизация работают')},function(err){notify('HDREZKA: '+err)})},function(err){notify('HDREZKA: '+err)})}catch(e){notify('HDREZKA: '+String(e.message||e))}}
function settingsIcon(){return'<svg viewBox="0 0 24 24" width="28" height="28" fill="currentColor"><path d="M8 5h8l1 2h3v4h-2.1a6 6 0 0 1 0 2H20v4h-3l-1 2H8l-1-2H4v-4h2.1a6 6 0 0 1 0-2H4V7h3l1-2Zm4 4a3 3 0 1 0 0 6 3 3 0 0 0 0-6Z"/></svg>'}
function resetSettingsRegistry(){try{return !!(window.rezka4_register_settings&&window.rezka4_register_settings(true))}catch(e){console.log('REZKA4 settings reset error',e);return false}}
function scheduleSettingsRepair(){if(window.rezka4_settings_registry_fixed)return;var tries=0;function step(){if(resetSettingsRegistry()){window.rezka4_settings_registry_fixed=true;return}if(tries++<40)setTimeout(step,250)}step()}
function refresh(){syncMovie();bindChoices();showEpisodeProgress();showSeasonProgress()}
function scheduleRefresh(delay){clearTimeout(refreshTimer);refreshTimer=setTimeout(function(){refreshTimer=0;refresh()},Math.max(0,delay||0))}
window.rezka4_history_api={version:3,roadFor:roadFor,episodeStates:episodeStates,seasonSummary:seasonSummary,titleSummary:titleSummary,pickResume:pickResume,pickEpisode:pickEpisode,pickTarget:pickTarget,pickSeason:pickSeason,setCatalog:setCatalog,setSelection:setSelection,refresh:refresh};
function install(){try{ensureStyle();scheduleSettingsRepair();hookPlayer();installPlayerEpisodeNav();refresh();if(typeof MutationObserver!=='undefined'&&document.body){var o=new MutationObserver(function(){scheduleRefresh(35)});o.observe(document.body,{childList:true,subtree:true});window.rezka4_history_observer=o}if(Lampa.Listener){Lampa.Listener.follow('full',function(){scheduleRefresh(30)});Lampa.Listener.follow('activity',function(){scheduleRefresh(30)});Lampa.Listener.follow('player',function(){scheduleRefresh(80)});Lampa.Listener.follow('app',function(e){if(e&&e.type==='ready')setTimeout(scheduleSettingsRepair,20)})}if(Lampa.Player&&Lampa.Player.listener&&Lampa.Player.listener.follow)Lampa.Player.listener.follow('destroy',function(){scheduleRefresh(80)})}catch(e){console.log('REZKA4 history install error',e)}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install,{once:true});else install();
})();