/* HDREZKA plugin for Lampa v4.0.0 - create() starts network */
(function(){
'use strict';
if(window.rezka4_plugin_ready)return;window.rezka4_plugin_ready=true;
var DOMAIN='https://kvk.pub';
var PROXY='https://lampa.datalab.md/?url=';
function proxify(url){return PROXY+encodeURIComponent(url);}
function xhr(method,url,body,ok,fail){try{var x=new XMLHttpRequest();x.open(method,proxify(url),true);x.timeout=20000;x.setRequestHeader('X-Requested-With','XMLHttpRequest');if(method==='POST')x.setRequestHeader('Content-Type','application/x-www-form-urlencoded');x.onload=function(){if(x.status>=200&&x.status<300)ok(x.responseText,x);else if(fail)fail('HTTP '+x.status);};x.onerror=function(){if(fail)fail('Сетевая ошибка');};x.ontimeout=function(){if(fail)fail('Таймаут');};x.send(body||null);}catch(e){if(fail)fail(e.message);}}
function abs(href){try{return new URL(href,DOMAIN+'/').toString();}catch(e){return href;}}
function searchRezka(q,year,cb,fail){xhr('GET',DOMAIN+'/engine/ajax/search.php?q='+encodeURIComponent(q),null,function(html){var d=document.createElement('div');d.innerHTML=html;var arr=[];d.querySelectorAll('a').forEach(function(el){var href=el.getAttribute('href');if(!href||href.indexOf('search')!==-1)return;var full=(el.textContent||'').trim();var enty=el.querySelector('.enty');var title=enty?(enty.textContent||'').trim():full;var ym=full.match(/\b(19|20)\d{2}\b/);arr.push({url:abs(href),title:title,year:ym?ym[0]:''});});if(year){var exact=arr.filter(function(i){return i.year==String(year);});if(exact.length)arr=exact;}cb(arr);},fail);}
function fetchFilmPage(url,cb,fail){xhr('GET',url,null,function(str){var info={film_id:'',is_series:false,favs:'',voice:[],season:[],episode:[]};var m=str.match(/initCDN(?:Series|Movies)Events\(\s*(\d+)\s*,\s*(\d+)\s*,\s*([01])\s*,\s*([01])\s*(?:,\s*([01]))?/);if(!m){fail('Не удалось распарсить страницу');return;}info.film_id=m[1];var def=m[2],cam=m[3],ads=m[4],dir=m[5]||'0';info.is_series=/initCDNSeriesEvents/.test(str);var fm=str.match(/data-favs="([^"]+)"/);if(fm)info.favs=fm[1];var tm=str.match(/<ul[^>]+class="b-translator__list"[\s\S]*?<\/ul>/);if(tm){var td=document.createElement('div');td.innerHTML=tm[0];td.querySelectorAll('.b-translator__item').forEach(function(li){info.voice.push({name:(li.getAttribute('title')||li.textContent||'').trim(),id:li.getAttribute('data-translator_id')||def,is_camrip:li.getAttribute('data-camrip')||cam,is_ads:li.getAttribute('data-ads')||ads,is_director:li.getAttribute('data-director')||dir});});}if(!info.voice.length)info.voice.push({name:'Оригинал',id:def,is_camrip:cam,is_ads:ads,is_director:dir});if(info.is_series){var sm=str.match(/<ul[^>]+class="b-simple_seasons__list"[\s\S]*?<\/ul>/);if(sm){var sd=document.createElement('div');sd.innerHTML=sm[0];sd.querySelectorAll('.b-simple_season__item').forEach(function(li){info.season.push({name:(li.textContent||'').trim(),id:li.getAttribute('data-tab_id')});});}var em=str.match(/<ul[^>]+class="b-simple_episodes__list"[\s\S]*?<\/ul>/g);if(em)em.forEach(function(block){var ed=document.createElement('div');ed.innerHTML=block;ed.querySelectorAll('.b-simple_episode__item').forEach(function(li){info.episode.push({name:(li.textContent||'').trim(),season_id:li.getAttribute('data-season_id'),episode_id:li.getAttribute('data-episode_id')});});});}cb(info);},fail);}
function decodeTrash(data){if(!data||typeof data!=='string'||data.charAt(0)!=='#')return data;var trash=['$$!!@$$@^!@#$$@','@@@@@!##!^^^','####^!!##!@@','^^^!@##!!##','$$#!!@#!@##'];function enc(s){return btoa(unescape(encodeURIComponent(s)));}var x=data.substring(2);trash.forEach(function(t){x=x.split('//_//'+enc(t)).join('');});try{return decodeURIComponent(escape(atob(x)));}catch(e){try{return atob(x);}catch(e2){return '';}}}
function playlist(s){if(!s)return[];return s.split(',').map(function(p){var m=p.match(/\[([^\]]+)\](.+)/);if(!m)return null;var u=m[2].split(' or ');return{label:m[1].trim(),file:u[u.length-1].trim()};}).filter(Boolean);}
function getStream(info,voice,season,episode,cb,fail){var body;if(info.is_series&&season&&episode){body='id='+encodeURIComponent(info.film_id)+'&translator_id='+encodeURIComponent(voice.id)+'&season='+encodeURIComponent(season.id)+'&episode='+encodeURIComponent(episode.episode_id)+'&favs='+encodeURIComponent(info.favs||'')+'&action=get_stream';}else{body='id='+encodeURIComponent(info.film_id)+'&translator_id='+encodeURIComponent(voice.id)+'&is_camrip='+encodeURIComponent(voice.is_camrip||0)+'&is_ads='+encodeURIComponent(voice.is_ads||0)+'&is_director='+encodeURIComponent(voice.is_director||0)+'&favs='+encodeURIComponent(info.favs||'')+'&action=get_movie';}xhr('POST',DOMAIN+'/ajax/get_cdn_series/?t='+Date.now(),body,function(t){var j;try{j=JSON.parse(t);}catch(e){fail('Некорректный JSON');return;}if(!j||!j.success){fail((j&&j.message)||'Сервер вернул ошибку');return;}var arr=playlist(decodeTrash(j.url));if(!arr.length){fail('Пустой плейлист');return;}var q={};arr.forEach(function(i){q[i.label]=i.file;});cb({file:arr[arr.length-1].file,quality:q});},fail);}
function component(object){var scroll=new Lampa.Scroll({mask:true,over:true});var files=new Lampa.Explorer(object);var html=$('<div></div>');var self=this;var started=false;function show(msg){html.empty();var e=new Lampa.Empty({text:msg});html.append(e.render());scroll.append(html);Lampa.Controller.enable('content');}function load(){if(started)return;started=true;try{self.activity.loader(true);}catch(e){}var m=object.movie||{},title=m.title||m.name||'',year=(m.release_date||m.first_air_date||'').slice(0,4);searchRezka(title,year,function(r){if(!r.length){try{self.activity.loader(false);}catch(e){}show('Ничего не найдено на HDREZKA');return;}fetchFilmPage(r[0].url,function(info){try{self.activity.loader(false);}catch(e){}html.empty();var voice=info.voice[0];var items=info.is_series&&info.season.length?info.episode.filter(function(ep){return String(ep.season_id)===String(info.season[0].id);}):[{name:'Смотреть фильм'}];items.forEach(function(ep){var item=$('<div class="online"><div class="online__title">'+Lampa.Utils.escape(ep.name)+'</div><div class="online__quality">'+Lampa.Utils.escape(voice.name)+'</div></div>');item.on('hover:enter',function(){getStream(info,voice,info.is_series?info.season[0]:null,info.is_series?ep:null,function(d){var p={url:d.file,title:title,quality:d.quality};Lampa.Player.play(p);Lampa.Player.playlist([p]);},function(msg){Lampa.Noty.show('HDREZKA: '+msg);});});html.append(item);});scroll.append(html);Lampa.Controller.enable('content');},function(msg){try{self.activity.loader(false);}catch(e){}show(msg);});},function(msg){try{self.activity.loader(false);}catch(e){}show(msg);});}
this.create=function(){scroll.minus();files.appendFiles(scroll.render());setTimeout(load,0);return files.render();};this.render=function(){return files.render();};this.start=function(){Lampa.Controller.add('content',{toggle:function(){Lampa.Controller.collectionSet(scroll.render(),files.render());Lampa.Controller.collectionFocus(false,scroll.render());},up:function(){Lampa.Controller.toggle('head');},down:function(){Navigator.move('down');},left:function(){Lampa.Controller.toggle('menu');},right:function(){Navigator.move('right');},back:this.back});Lampa.Controller.toggle('content');};this.pause=function(){};this.stop=function(){};this.back=function(){Lampa.Activity.backward();};this.destroy=function(){scroll.destroy();files.destroy();html.remove();};}
function openRezka(movie){Lampa.Activity.push({url:'',title:'HDREZKA - '+(movie.title||movie.name||''),component:'rezka4_online',movie:movie,page:1});}
function start(){if(window.rezka4_plugin_started)return;window.rezka4_plugin_started=true;Lampa.Component.add('rezka4_online',component);Lampa.Listener.follow('full',function(e){if(e.type!=='complite')return;var root=e.object.activity.render();var c=root.find('.full-start-new__buttons');if(!c.length)c=root.find('.full-start__buttons');if(!c.length||root.find('.view--rezka4').length)return;var b=$('<div class="full-start__button selector view--online view--rezka4"><span>HDREZKA</span></div>');b.on('hover:enter',function(){openRezka(e.data.movie);});c.prepend(b);});console.log('REZKA4 started');}
function boot(){if(typeof Lampa==='undefined')return setTimeout(boot,200);if(window.appready)start();else if(Lampa.Listener&&Lampa.Listener.follow){Lampa.Listener.follow('app',function(e){if(e.type==='ready')start();});setTimeout(function(){if(window.appready)start();},1000);}else start();}
boot();
})();