import express from 'express';
const app=express();app.set('trust proxy',true);app.use(express.raw({type:'*/*',limit:'2mb'}));
const PORT=Number(process.env.PORT||3000),hosts=new Set(['kvk.pub','rezka.fi']),sessions=new Map(),recent=[];let latestAuthKey='',pluginCache='',pluginLastError='',pluginSource='';
const STABLE_PLUGIN_COMMIT='5e009bf00cc763cc6da55cbd7871fdfeb2cf8327';
const STABLE_ADDON_COMMIT='6821a8b38896c29a2519272580fa3b2539ef212f';
function k(q){const sid=String(q.headers['x-lampa-session']||'').trim();if(sid)return 'sid:'+sid;return`${String(q.headers['x-forwarded-for']||q.ip).split(',')[0]}|${q.headers['user-agent']||''}`}
function ss(q){let key=k(q),x=sessions.get(key);if(!x){x={c:new Map(),updated:Date.now(),referer:'https://kvk.pub/'};sessions.set(key,x)}x.updated=Date.now();return x}
function ck(x){return[...x.c].map(([a,b])=>a+'='+b).join('; ')}
function sc(x,r,key){let a=typeof r.headers.getSetCookie==='function'?r.headers.getSetCookie():[r.headers.get('set-cookie')].filter(Boolean);a.forEach(z=>{let f=z.split(';')[0],i=f.indexOf('=');if(i>0)x.c.set(f.slice(0,i),f.slice(i+1))});if(x.c.has('dle_user_id')&&key)latestAuthKey=key}
function safeReferer(q,x){let ref=String(q?.headers?.['x-rezka-referer']||'').trim()||x?.referer||'https://kvk.pub/';try{let u=new URL(ref);return hosts.has(u.hostname.toLowerCase())?u.toString():'https://kvk.pub/'}catch{return'https://kvk.pub/'}}
function hd(u,x,q){let ref=safeReferer(q,x),origin='https://kvk.pub';try{origin=new URL(ref).origin}catch{}let h=new Headers({'User-Agent':'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 Chrome/124 Safari/537.36','Accept':'application/json, text/javascript, */*; q=0.01','Cache-Control':'no-cache','Pragma':'no-cache','Referer':ref,'Origin':origin,'X-Requested-With':'XMLHttpRequest'});if(ck(x))h.set('Cookie',ck(x));return h}
function streamDiag(q,u,b){if(!/\/ajax\/get_cdn_series\/?$/i.test(u.pathname))return{};let req={};try{let p=new URLSearchParams((q.body||Buffer.alloc(0)).toString('utf8'));req={action:p.get('action')||'',id:p.get('id')||'',translator_id:p.get('translator_id')||'',season:p.get('season')||'',episode:p.get('episode')||'',has_favs:!!p.get('favs')}}catch{}let rezka={};try{let j=JSON.parse(b.toString('utf8'));rezka={success:j?.success,message:String(j?.message||'').replace(/<[^>]*>/g,' ').replace(/\s+/g,' ').trim().slice(0,300),has_url:!!j?.url}}catch{}return{request:req,rezka}}
app.use((q,s,n)=>{s.set('Access-Control-Allow-Origin','*');s.set('Access-Control-Allow-Headers','Content-Type,X-Requested-With,X-Lampa-Session,X-Rezka-Referer');s.set('Access-Control-Allow-Methods','GET,POST,OPTIONS');if(q.method==='OPTIONS')return s.sendStatus(204);n()});
app.get('/health',(q,s)=>s.json({ok:true,latestAuth:!!latestAuthKey,pluginCached:!!pluginCache,pluginSource,pluginLastError,stablePluginCommit:STABLE_PLUGIN_COMMIT,stableAddonCommit:STABLE_ADDON_COMMIT,sessions:sessions.size}));app.get('/debug/recent',(q,s)=>s.json({ok:true,recent}));
async function fetchFirst(urls,minSize){let errors=[];for(const url of urls){try{const r=await fetch(url,{headers:{'User-Agent':'lampa-plugin-proxy','Cache-Control':'no-cache'},cache:'no-store'});if(!r.ok)throw new Error('HTTP '+r.status);const code=await r.text();if(!code||code.length<(minSize||1))throw new Error('response too small: '+code.length);return{code,host:new URL(url).hostname}}catch(e){errors.push(new URL(url).hostname+': '+String(e?.message||e))}}throw new Error(errors.join(' | '))}
async function loadPlugin(){const baseUrls=[`https://cdn.jsdelivr.net/gh/datalabMD/lampa-plugins@${STABLE_PLUGIN_COMMIT}/rezka4.js`,`https://raw.githubusercontent.com/datalabMD/lampa-plugins/${STABLE_PLUGIN_COMMIT}/rezka4.js`];let base;try{base=await fetchFirst(baseUrls,15000);new Function(base.code)}catch(e){pluginLastError=String(e?.message||e);throw e}let finalCode=base.code,source=base.host+'@stable',warning='';const addonUrls=[`https://cdn.jsdelivr.net/gh/datalabMD/lampa-plugins@${STABLE_ADDON_COMMIT}/source-addon.js`,`https://raw.githubusercontent.com/datalabMD/lampa-plugins/${STABLE_ADDON_COMMIT}/source-addon.js`];try{const addon=await fetchFirst(addonUrls,100);const candidate=base.code+'\n'+addon.code;new Function(candidate);finalCode=candidate;source=source+'+'+addon.host+'@stable'}catch(e){warning='addon skipped: '+String(e?.message||e)}pluginCache=finalCode;pluginSource=source;pluginLastError=warning;return finalCode}
app.get('/plugin.js',async(q,s)=>{try{const code=await loadPlugin();s.type('application/javascript').set('Cache-Control','no-store, no-cache, must-revalidate').send(code)}catch(e){if(pluginCache)return s.type('application/javascript').set('Cache-Control','no-store').send(pluginCache);s.status(502).type('text/plain').send('plugin load failed: '+String(e?.message||e))}});
app.get('/debug/page',async(q,s)=>{try{let u=new URL(String(q.query.url||'https://kvk.pub/films/fantasy/85038-odisseya-2026.html')),x=latestAuthKey&&sessions.get(latestAuthKey);if(!x)return s.status(409).json({ok:false,error:'No authenticated Lampa session yet'});x.referer=u.toString();let r=await fetch(u,{headers:hd(u,x,q),redirect:'follow'});sc(x,r,latestAuthKey);let t=await r.text(),tokens=[...t.matchAll(/.{0,140}(?:translator|cdn|player|sof\.tv|post_id|post-id|data-id|iframe|video).{0,260}/gi)].slice(0,40).map(m=>m[0]),attrs=[...t.matchAll(/<(?:div|li|input|script|span)[^>]{0,650}(?:translator|cdn|player|post|video)[^>]*>/gi)].slice(0,40).map(m=>m[0]);s.json({ok:true,bytes:t.length,title:(t.match(/<title[^>]*>(.*?)<\/title>/is)||[])[1]||'',cookies:[...x.c.keys()],tokens,attrs})}catch(e){s.status(500).json({error:String(e)})}});
function tu(q){let z=String(q.query.url||'');try{z=decodeURIComponent(z)}catch{};try{let u=new URL(z);return hosts.has(u.hostname)?u:null}catch{return null}}
app.all('*',async(q,s)=>{let u=tu(q);if(!u)return s.status(400).json({error:'target'});let key=k(q),x=ss(q);if(q.method==='GET'&&/^\/(?:series|films|animation)\//i.test(u.pathname))x.referer=u.toString();let h=hd(u,x,q);if(q.headers['content-type'])h.set('Content-Type',q.headers['content-type']);let i={method:q.method,headers:h,redirect:'follow'};if(!['GET','HEAD'].includes(q.method)&&q.body?.length)i.body=q.body;try{let r=await fetch(u,i);sc(x,r,key);let b=Buffer.from(await r.arrayBuffer()),diag=streamDiag(q,u,b);recent.unshift({time:new Date().toISOString(),method:q.method,target:u.toString(),status:r.status,bytes:b.length,cookies:[...x.c.keys()],session:key.slice(0,28),referer:h.get('Referer'),...diag});recent.length=Math.min(recent.length,40);s.status(r.status).set('Content-Type',r.headers.get('content-type')||'text/plain').set('Cache-Control','no-store').send(b)}catch(e){s.status(502).json({error:String(e)})}});
app.listen(PORT,'0.0.0.0');